#!/Users/meriy100/.rbenv/shims/ruby
shresult = `pmset -g ps`
s = shresult.match /Now drawing from '(?<from>\w+ \w+)'/
if s[:from] == "AC Power"
  print "\e[32m"
  print "⚡︎"
end
print "\e[0m"
shresult.match /(\d+)%;/ do |m|
  case m[1].to_i
  when 0..30
    print "\e[31m"
  when 31..60
    print "\e[33m"
  when 61..99
    print "\e[32m"
  when 100
    print "\e[34m"
  end
  print "#{m[1]}%"
  print "\e[34m"
end

