#!/Users/meriy100/.rbenv/shims/ruby
shresult = `pmset -g ps`
s = shresult.match /Now drawing from '(?<from>\w+ \w+)'/
status = s[:from] == "AC Power" ? "⚡︎" : "❚"
shresult.match /(\d+)%;/ do |m|
  case m[1].to_i
  when 0..30
    print "#[fg=colour196]"
    print status * 1
  when 31..60
    print "#[fg=colour220]"
    print status * 2
  when 61..99
    print "#[fg=colour46]"
    print status * 3
  when 100
    print "#[fg=colour21]"
    print status * 3
  end
  print "#{m[1]}%"
  print "#[default]"
end

